# Generated by Django 5.1.1 on 2024-10-06 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('link_insta', models.URLField(blank=True, null=True)),
                ('link_facebook', models.URLField(blank=True, null=True)),
                ('link_ext', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nbr_max_personnes', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='studios/')),
            ],
        ),
        migrations.CreateModel(
            name='StudioDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('date_achat', models.DateField()),
                ('type_appareil', models.CharField(choices=[('ampli', 'Amplificateur'), ('baffle guitare', 'Baffle guitare'), ('baffle basse', 'Baffle basse'), ('batterie', 'Batterie')], max_length=50)),
                ('duree_garantie_annees', models.PositiveIntegerField()),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='website.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField()),
                ('description', models.TextField()),
                ('studio_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='website.studiodevice')),
            ],
        ),
    ]
