# Generated by Django 5.2.3 on 2025-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_news_options_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiodevice',
            name='esp_id',
            field=models.CharField(default='default-esp-id', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiodevice',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
