# Generated by Django 5.2.3 on 2025-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_studiodevice_esp_id_studiodevice_is_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioESP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('esp_ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('ON', 'Allumé'), ('OFF', 'Éteint')], default='OFF', max_length=10)),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
    ]
