# Generated by Django 5.2.3 on 2025-06-19 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_espcommand_studioesp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioesp',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studioesp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studioesp',
            name='status',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10),
        ),
    ]
