# Generated by Django 5.2.3 on 2025-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_studioesp_last_ping_alter_studioesp_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studioesp',
            name='connected',
        ),
        migrations.RemoveField(
            model_name='studioesp',
            name='last_ping',
        ),
        migrations.AddField(
            model_name='studioesp',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioesp',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
