# Generated by Django 5.2.3 on 2025-06-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_studioesp_connected_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESPCommand',
        ),
        migrations.RemoveField(
            model_name='studioesp',
            name='status',
        ),
        migrations.AddField(
            model_name='studioesp',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
