# Generated by Django 5.2.3 on 2025-06-20 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_espcommand_remove_studioesp_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entretien',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RenameField(
            model_name='studioesp',
            old_name='esp_ip',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='date_entretien',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='studio_device',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link_ext',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link_insta',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='nbr_max_personnes',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='duree_garantie_annees',
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='esp_id',
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='type_appareil',
        ),
        migrations.RemoveField(
            model_name='studioesp',
            name='state',
        ),
        migrations.AddField(
            model_name='entretien',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entretien',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.studio'),
        ),
        migrations.AddField(
            model_name='studio',
            name='etat',
            field=models.CharField(choices=[('free', 'Libre'), ('busy', 'Pris / Occupé')], default='free', max_length=4),
        ),
        migrations.AddField(
            model_name='studio',
            name='photo',
            field=models.ImageField(blank=True, upload_to='studios/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='surface_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='studiodevice',
            name='esp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.studioesp'),
        ),
        migrations.AddField(
            model_name='studiodevice',
            name='hs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studiodevice',
            name='type',
            field=models.CharField(choices=[('ampli', 'Amplificateur'), ('baffle_guitare', 'Baffle guitare'), ('baffle_basse', 'Baffle basse'), ('batterie', 'Batterie')], default='ampli', max_length=20),
        ),
        migrations.AddField(
            model_name='studioesp',
            name='role',
            field=models.CharField(choices=[('clock', 'Horloge'), ('relay', 'Relais'), ('other', 'Autre')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='studioesp',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esps', to='website.studio'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
