# Generated by Django 5.2.3 on 2025-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_entretien_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['ordre_tri']},
        ),
        migrations.AddField(
            model_name='studio',
            name='ordre_tri',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studio',
            name='pano',
            field=models.ImageField(blank=True, upload_to='360/'),
        ),
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='vignette',
            field=models.ImageField(blank=True, upload_to='studios/'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='surface_m2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
