# Generated by Django 5.2.3 on 2025-06-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_studio_options_studio_ordre_tri_studio_pano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioesp',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
