# Generated by Django 5.2.3 on 2025-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_studioesp_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiodevice',
            name='type',
            field=models.CharField(choices=[('console', 'Console'), ('processeur', 'Processeur'), ('ampli', 'Ampli'), ('sortie_aux', 'Sortie auxiliaire'), ('relais_xlr', 'Relais XLR')], default='ampli', max_length=20),
        ),
    ]
