# Generated by Django 5.2.3 on 2025-06-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_studiodevice_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studiodevice',
            old_name='type',
            new_name='device',
        ),
    ]
