# Generated by Django 5.2.3 on 2025-06-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_type_studiodevice_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='esp',
        ),
        migrations.RemoveField(
            model_name='studiodevice',
            name='studio',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='pano',
            new_name='panoramic',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='surface_m2',
            new_name='surface',
        ),
        migrations.RemoveField(
            model_name='studioesp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studioesp',
            name='state',
        ),
        migrations.AddField(
            model_name='studio',
            name='calendar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studioesp',
            name='status',
            field=models.CharField(default='is_off', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studio',
            name='etat',
            field=models.CharField(default='free', max_length=4),
        ),
        migrations.AlterField(
            model_name='studio',
            name='ordre_tri',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studioesp',
            name='role',
            field=models.CharField(default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='studioesp',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.studio'),
        ),
        migrations.CreateModel(
            name='EnrollmentUserMusicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('music_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.musicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudioEspDisplayDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='display', max_length=20)),
                ('is_on', models.BooleanField(default=False)),
                ('esp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.studioesp')),
            ],
        ),
        migrations.CreateModel(
            name='StudioEspRackDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ampli', max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('esp_output_id', models.IntegerField()),
                ('is_on', models.BooleanField(default=False)),
                ('esp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.studioesp')),
            ],
        ),
        migrations.DeleteModel(
            name='Entretien',
        ),
        migrations.DeleteModel(
            name='StudioDevice',
        ),
    ]
