# Generated by Django 5.2.3 on 2025-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_musicgroup_remove_studiodevice_esp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioesp',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
