# Generated by Django 5.2.3 on 2025-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_studioesp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='photo',
        ),
        migrations.AddField(
            model_name='studioesp',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
