# Generated by Django 5.2.3 on 2025-06-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_studio_photo_studioesp_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du calendrier')),
                ('google_id', models.CharField(blank=True, help_text='L’ID Google (ex. votre@mail.com).', max_length=255, null=True, verbose_name='Google Calendar ID')),
            ],
            options={
                'verbose_name': 'Calendrier',
                'verbose_name_plural': 'Calendriers',
            },
        ),
        migrations.RemoveField(
            model_name='studioesp',
            name='connected',
        ),
        migrations.AlterField(
            model_name='studioesp',
            name='status',
            field=models.CharField(choices=[('is_on', 'On'), ('is_off', 'Off')], max_length=16),
        ),
        migrations.AlterField(
            model_name='studio',
            name='calendar',
            field=models.ForeignKey(blank=True, help_text='Choisir le calendrier lié à ce studio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studios', to='website.calendar', verbose_name='Calendrier associé'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('is_available', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.calendar')),
            ],
        ),
    ]
