# Generated by Django 5.2.3 on 2025-06-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_calendar_remove_studioesp_connected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de l’appareil')),
                ('category', models.CharField(choices=[('string', 'Cordes'), ('amp', 'Amplification'), ('drum', 'Percussions'), ('misc', 'Divers')], default='misc', max_length=20, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Détails / quantité')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre d’affichage')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='website.studio', verbose_name='Studio')),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
                'ordering': ['order', 'name'],
            },
        ),
    ]
