# Generated by Django 5.2.3 on 2025-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['order', 'brand'], 'verbose_name': 'Appareil', 'verbose_name_plural': 'Appareils'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='brand',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('string', 'Cordes'), ('amp', 'Amplification'), ('drum', 'Percussions'), ('misc', 'Divers')], default='New', max_length=20, verbose_name='Etat'),
        ),
    ]
